### ISSUE TITLE
Can you share the preprocessed data?

### ISSUE THREAD

**Issue by heyuanpengpku** [AronCao49/Latte#1]
Great work! However, the raw data is too large for our server to download. 
Could you please share the preprocessed data? 
Looking forward to your reply!

**Comment by AronCao49** [comment]
Thanks for your interest in this work! Unfortunately, directly sharing the preprocessed version of licensed datasets (e.g., NuScenes) could be illegitimate. I am not so sure about the cases for each dataset we used, but the safest way seems to be sharing the preprocessing procedure by now.

**Comment by AronCao49** [comment]
Issue closed. If you need any other help, pls let me know :)
